### ISSUE TITLE
Naming + open sourcing.

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/forza#2]
This issue is about finding a better name than estragon (which is the last step before open-sourcing).
- `clef`
- `drone`

**Comment by jcrugzz** [comment]
I'd keep it with the musical theming personally. What do you think of `tremolo`. The definition made sense for the data emitting aspect. 

> shaking; i.e., a rapid repetition of the same note, or an alternation between two or more notes (often an octave on the piano)

**Comment by AvianFlu** [comment]
Don't use any of these names, I'll come up with one tomorrow.  I've been around crazy musical terms longer than most of the rest of the people involved in this, and I'll understand the appropriate context better.

**Comment by yawnt** [comment]
@jcrugzz not, it sounds super funny (and a bit ridiculous) for italian people.. even though it's musical :D

**Comment by mmalecki** [comment]
@AvianFlu any progress with the name?

**Comment by mmalecki** [comment]
@AvianFlu ping?

**Comment by indexzero** [comment]
#### Brain dump

After [reading this](https://en.wikipedia.org/wiki/Glossary_of_musical_terminology) I compiled a list of possible names, _in no particular order:_
- `animato`: animated, lively
- `forza` : musical force
- `legato`: joined; i.e., smoothly, in a connected manner
- `magico`: magically
- `magnifico`: magnificent
- `meter` (or `metre`): the pattern of a music piece's rhythm of strong and weak beats
- `moto`: motion; usually seen as `con moto`, meaning with motion or quickly
- `pezzo`: a composition
- `poco`: a little, as in `poco più allegro` (a little faster)
- `rapido`: fast
- `soave`: smoothly, gently
- `tosto`: rapidly

As _most of this looks like Italian_ I am going to summon @yawnt for his input on what words are just silly.

**Comment by indexzero** [comment]
cc/ @AvianFlu

**Comment by yawnt** [comment]
`animato`, `legato`, `magico`, `magnifico`, `rapido`, `soave` and `tosto` are all adjectives.. so  they all sound a bit funny because it'd be like naming your lib "fast" or "strong" etc

`tosto` is either "i toast" or "badass" in italian.. i like the badass reference :D 
`moto` is movement yes, but it also means `motorcycle` (which is way more used)
`forza` means strength
`magico` is magic (adjective, not noun), not magically (that'd be `magicamente` which isn't very used)
`metre` isn't italian but i think people would be reminded of the actual meter
`legato` means `tied up` 
`pezzo` is either composition or simply `piece` (which again is more common unless you are talking specifically about music)
`poco` is (as you said) `a tiny bit`, so it doesn't look really fit for a library name to me :P

**Comment by yawnt** [comment]
also "toast" as in toasted bread, not related at all to what you do before you drink wine

**Comment by mmalecki** [comment]
The king is dead, long live the king!
