### ISSUE TITLE
Listening to the subdomain

### ISSUE THREAD

**Issue by Swaagie** [nodejitsu/forza#22]
Not sure if this is intentional or just a minor issue or has never worked before either. Today I noticed two people had `express` listening to the subdomain, e.g:

```
server.listen(8080, anydomain.jitsu.com, function () {
```

This will prevent the app from starting. As soon as the subdomain is omitted (which is perfectly valid), the application will start normally.

**Comment by Swaagie** [comment]
Note the main question is, how many people do this and can we check against it or should they just listen to localhost (default)

**Comment by mmalecki** [comment]
This might've worked before because in `haibu-carapace` we'd override the host part to `0.0.0.0`, which means 'listen on all interfaces'. `127.0.0.1` isn't the default and it means 'only listen on local network interface'.

Anyway, what those apps are doing is really stupid. We should either override this to `0.0.0.0` or be very clear that this is wrong. I'd prefer telling people (as a learning experience for them).

**Comment by Swaagie** [comment]
Agree on the telling and learning, might FAQ this stuff then, as some 
other providers do require this kind of stuff. Basically we are KISS and 
the others are bloated.

**Comment by mmalecki** [comment]
Fixed in 2c2666293a9becb4e84d6176ba8a4a70a3b69dd2 and 0894dcfeca485591f02ca9f3cf5ace8ac153d329.
